[package]
name = "Elk"
version = "0.1.0"
authors = ["CSy-n <alpha.phonecian@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sdl2="0.34.5"
lua53-sys="0.1.1"
libc = "0.2"
